In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import *


In [ ]:
!ls /content/drive/MyDrive/kuliah/Smester\ \5/big\ \data\ \&\ \data\ \mining/p9/

data_test.csv	 p9-klasifikasi.ipynb	 StudentPerformance-encoded.csv
data_train.xlsx  Social_Network_Ads.csv


binary classification

In [ ]:
df = pd.read_csv("/content/Social_Network_Ads (1).csv")
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/kuliah/Smester 5/big data & data mining/p9/Social_Network_Ads.csv")
df.head()


User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [ ]:
# x adalah variabel independen = berisi Age dan estimated salary
X = df.iloc[:, [2, 3]].values
# y adalah variabel dependen = berisi fitur purchased
y = df.iloc[:, -1].values

df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [ ]:
# menampilkan isi variabel x dan y 
#print(X)
#print(y)

print(f"X: \n {X[:5]}")
print(f"Y: \n {y[:5]}")

X: 
 [[   19 19000]
 [   35 20000]
 [   26 43000]
 [   27 57000]
 [   19 76000]]
Y: 
 [0 0 0 0 0]


In [ ]:
X.shape

(400, 2)

In [ ]:
# splitting data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [ ]:
print(X_train.shape)
print(X_test.shape)

(320, 2)
(80, 2)


MEMBUAT MODEL KLASIFIKASI

In [ ]:
# training the naive bayes model on the training set

classifier_model_binary = GaussianNB()
classifier_model_binary.fit(X_train, y_train)

GaussianNB()

PREDICT TEST

In [ ]:
y_pred = classifier_model_binary.predict(X_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1])

In [ ]:
classifier_model_binary.predict_proba(X_test)

array([[0.89147043, 0.10852957],
       [0.84097849, 0.15902151],
       [0.85177346, 0.14822654],
       [0.91910807, 0.08089193],
       [0.89836193, 0.10163807],
       [0.95434022, 0.04565978],
       [0.90414431, 0.09585569],
       [0.03556946, 0.96443054],
       [0.98918806, 0.01081194],
       [0.50281633, 0.49718367],
       [0.95249262, 0.04750738],
       [0.96371556, 0.03628444],
       [0.85930139, 0.14069861],
       [0.7299999 , 0.2700001 ],
       [0.97431305, 0.02568695],
       [0.47994231, 0.52005769],
       [0.79297558, 0.20702442],
       [0.97847631, 0.02152369],
       [0.00422727, 0.99577273],
       [0.86019336, 0.13980664],
       [0.89871448, 0.10128552],
       [0.00500754, 0.99499246],
       [0.75594755, 0.24405245],
       [0.13376637, 0.86623363],
       [0.97909645, 0.02090355],
       [0.0047035 , 0.9952965 ],
       [0.9182418 , 0.0817582 ],
       [0.92764915, 0.07235085],
       [0.84823267, 0.15176733],
       [0.86172083, 0.13827917],
       [0.

In [ ]:
def predict_one(age, salary):
  array_input = [[age, salary]]
  print("Probability : ", classifier_model_binary.predict_proba(array_input))

In [ ]:
def predict_Class(age, salary):
  array_input = [[age, salary]]
  print("Class : ", classifier_model_binary.predict(array_input))

In [ ]:
predict_Class(30,87000)

Class :  [0]


In [ ]:
predict_one(30,87000)

Probability :  [[0.89147043 0.10852957]]


In [ ]:
predict_Class(18,210000)

Class :  [1]


EVALUATE

In [ ]:
print(classification_report(y_test, y_pred, zero_division=0))

              precision    recall  f1-score   support

           0       0.93      0.97      0.95        58
           1       0.90      0.82      0.86        22

    accuracy                           0.93        80
   macro avg       0.92      0.89      0.90        80
weighted avg       0.92      0.93      0.92        80



In [ ]:
# making the confusion Matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[56,  2],
       [ 4, 18]])

2.  MULTI CLASS CLASSIFICATION

mengelompokkan data menjadi beberapa kelas (>2). Dataset di gunakan adalah sample data survei SNMPTN UI 2017 oleh 

In [ ]:
# read data
df_train = pd.read_excel("/content/drive/MyDrive/kuliah/Smester 5/big data & data mining/p9/data_train.xlsx")
df_test = pd.read_csv("/content/drive/MyDrive/kuliah/Smester 5/big data & data mining/p9/data_test.csv")

In [ ]:

print(df_train.shape)

(11, 6)


In [ ]:

print(df_test.shape)

(6, 6)


In [ ]:
df_train.head()

Jurusan  Matematika  Bahasa Inggris  Bahasa Indonesia  \
0      Matematika          92              86                88   
1      Matematika          90              86                85   
2  Sastra Inggris          82              87                92   
3      Matematika          93              82                85   
4  Sastra Inggris          86              85                88   

   Prestasi Siswa  Prestasi Sekolah  
0               1                 1  
1               1                 2  
2               2                 1  
3               1                 1  
4               1                 1

In [ ]:
df_test.head()

Jurusan  Matematika  Bahasa Inggris  Bahasa Indonesia  \
0        Matematika          92              82                85   
1        Matematika          91              83                85   
2    Sastra Inggris          82              80                88   
3  Sastra Indonesia          88              80                90   
4    Sastra Inggris          83              85                84   

   Prestasi Siswa  Prestasi Sekolah  
0               1                 1  
1               2                 2  
2               1                 1  
3               2                 1  
4               2                 1

In [ ]:
# data split
X_train = df_train.drop(["Jurusan"], axis=1)
y_train = df_train['Jurusan']

X_test = df_test.drop(["Jurusan"], axis=1)
y_test = df_test['Jurusan']

In [ ]:
y_train.head()

0        Matematika
1        Matematika
2    Sastra Inggris
3        Matematika
4    Sastra Inggris
Name: Jurusan, dtype: object

In [ ]:
X_train.head()

Matematika  Bahasa Inggris  Bahasa Indonesia  Prestasi Siswa  \
0          92              86                88               1   
1          90              86                85               1   
2          82              87                92               2   
3          93              82                85               1   
4          86              85                88               1   

   Prestasi Sekolah  
0                 1  
1                 2  
2                 1  
3                 1  
4                 1

4. Create Classifier Model

In [ ]:
# mengaktifkan / memanggil / membuat fungsi klasifikasi NAive bayes
classifier_model_multiclass = GaussianNB()

# memasukkan data training pada fungsi klasifikasi naive bayes
classifier_model_multiclass.fit(X_train, y_train)

GaussianNB()

In [ ]:
# training the naive bayes model on the training set

classifier_model_binary = GaussianNB()
classifier_model_binary.fit(X_train, y_train)

GaussianNB()

In [ ]:
y_pred = classifier_model_binary.predict(X_test)

In [ ]:
y_pred

array(['Matematika', 'Matematika', 'Sastra Indonesia', 'Sastra Indonesia',
       'Sastra Inggris', 'Sastra Indonesia'], dtype='<U16')

In [ ]:
classifier_model_binary.predict_proba(X_test)

array([[9.84514205e-01, 1.54850655e-02, 7.29022414e-07],
       [9.99987686e-01, 0.00000000e+00, 1.23143756e-05],
       [2.29659067e-20, 9.99999810e-01, 1.90218794e-07],
       [2.13516750e-09, 9.99999996e-01, 1.89843957e-09],
       [2.44441357e-13, 6.49045316e-06, 9.99993510e-01],
       [1.39716921e-06, 9.99998424e-01, 1.78428054e-07]])

In [ ]:
def predictProba(matematika, bahasaInggris, bahasaIndonesia, prestasiSiswa, prestasiSekolah):
  print(matematika, bahasaInggris, bahasaIndonesia, prestasiSiswa, prestasiSekolah)
  array_input = [[matematika, bahasaInggris, bahasaIndonesia, prestasiSiswa, prestasiSekolah]]
  print("Probability : ", classifier_model_binary.predict_proba(array_input))

In [ ]:
predictProba(92,82,85,1,1)

92 82 85 1 1
Probability :  [[9.84514205e-01 1.54850655e-02 7.29022414e-07]]


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  "X does not have valid feature names, but"


In [ ]:
def predict_Class(matematika, bahasaInggris, bahasaIndonesia, prestasiSiswa, prestasiSekolah):
  array_input = [[matematika, bahasaInggris, bahasaIndonesia, prestasiSiswa, prestasiSekolah]]
  print("Class : ", classifier_model_binary.predict(array_input))

In [ ]:
predict_Class(92,82,85,1,1)

Class :  ['Matematika']


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  "X does not have valid feature names, but"
